export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_FIELD = 'TOGGLE_FIELD';
export const ADD_ITEM = 'ADD_ITEM';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const DECREASE_CART_ITEM_QUANTITY = 'DECREASE_CART_ITEM_QUANTITY';
